component_depth: 1
languages:
- java
exclude:
- ./META-INF/.*
- ./lib/.*
- ./net/.*
- ./net/suberic/.*
- ./net/suberic/pooka/.*
- ./net/suberic/pooka/cache/.*
- ./net/suberic/pooka/conf/.*
- ./net/suberic/pooka/crypto/.*
- ./net/suberic/pooka/doc/.*
- ./net/suberic/pooka/doc/en/.*
- ./net/suberic/pooka/doc/en/help/.*
- ./net/suberic/pooka/doc/en/help/pooka/.*
- ./net/suberic/pooka/doc/en/help/pooka/addressbook/.*
- ./net/suberic/pooka/doc/en/help/pooka/config/.*
- ./net/suberic/pooka/doc/en/help/pooka/encryption/.*
- ./net/suberic/pooka/doc/en/help/pooka/images/.*
- ./net/suberic/pooka/doc/en/help/pooka/store/.*
- ./net/suberic/pooka/doc/en/help/pooka/ui/.*
- ./net/suberic/pooka/event/.*
- ./net/suberic/pooka/filter/.*
- ./net/suberic/pooka/gui/.*
- ./net/suberic/pooka/gui/crypto/.*
- ./net/suberic/pooka/gui/dnd/.*
- ./net/suberic/pooka/gui/filechooser/.*
- ./net/suberic/pooka/gui/filter/.*
- ./net/suberic/pooka/gui/images/.*
- ./net/suberic/pooka/gui/propedit/.*
- ./net/suberic/pooka/gui/search/.*
- ./net/suberic/pooka/htmlparser/.*
- ./net/suberic/pooka/jdbcaddr/.*
- ./net/suberic/pooka/ldap/.*
- ./net/suberic/pooka/messaging/.*
- ./net/suberic/pooka/ssl/.*
- ./net/suberic/pooka/thread/.*
- ./net/suberic/pooka/vcard/.*
- ./net/suberic/util/.*
- ./net/suberic/util/cache/.*
- ./net/suberic/util/event/.*
- ./net/suberic/util/gui/.*
- ./net/suberic/util/gui/images/.*
- ./net/suberic/util/gui/propedit/.*
- ./net/suberic/util/gui/propedit/images/.*
- ./net/suberic/util/prefs/.*
- ./net/suberic/util/swing/.*
- ./net/suberic/util/thread/.*
